services:
  # A Docker web service
  - type: web
    name: product-data-explorer-backend
    env: docker
    repo: https://github.com/kritikaspidy/Webscrapping.git
    region: singapore
    plan: free
    healthCheckPath: /
    # Add the following two lines to specify the Docker build context and path
    dockerContext: ./Backend/backend
    dockerfilePath: ./Backend/backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: products-db
          property: connectionString
      - key: PORT
        value: 3000

databases:
  # A PostgreSQL database
  - name: products-db
    databaseName: products
    user: db_user
    plan: free

