services:
  # A Docker web service
  - type: web
    name: product-data-explorer-backend
    env: docker
    repo: https://github.com/kritikaspidy/Webscrapping.git # Replace with your repo URL
    region: singapore # optional; choose a region close to you
    plan: free # optional
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: products-db
          property: connectionString
      - key: PORT
        value: 3000

databases:
  # A PostgreSQL database
  - name: products-db
    databaseName: products
    user: db_user
    plan: free
